# Generated by Django 4.2.7 on 2023-11-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_datahashorot_vaqt'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahashorot',
            name='vlajnost',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
