# Generated by Django 4.2.7 on 2023-11-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='hashorot_nomi',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
