# Generated by Django 4.2.7 on 2023-11-12 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_data_hashorot_nomi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='hashorot_nomi',
        ),
    ]
